name: spam2
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.15 # SVG 파일 열기
  cupertino_icons: ^1.0.8
  flutter_callkit_incoming: ^2.5.2
  uuid: ^4.5.1
  permission_handler: ^12.0.0+1
  dio: ^5.8.0+1 # HTTP
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.5.3 # 휴대폰 저장공간 사용

  hive: ^2.2.3 # NoSQL
  hive_flutter: ^1.1.0 # NoSQL 확장 패키지

  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^19.1.0

  flutter_slidable: ^4.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.7 # Hive 객체사용
  hive_generator: ^2.0.1 # Hive 객체사용

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/icons/flags/
    - assets/fonts/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700
    - family : Tmoney
      fonts :
        - asset: assets/fonts/TmoneyRoundWindRegular.otf
          weight: 500
        - asset : assets/fonts/TmoneyRoundWindExtraBold.otf
          weight: 600
